In [2]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer


###### ArCo ARMADO DE LA BASE#######
import os
from typing import List
from datetime import datetime

# Establecer el directorio de trabajo - DNP
#os.chdir("C:/Users/supegui/Documents/Metodología ArCo/Python/Excel")

# Establecer el directorio de trabajo - Remoto
os.chdir("C:/Backup - Archivos de trabajo/DNP/Automatización ArCo/Excel")


# Saca la lista de archivos del directorio de trabajo
#os.listdir()
# Obtener la fecha actual
fecha_actual = datetime.now().strftime("%Y %m %d")
#print(fecha_actual)

# Construir el nombre del archivo basado en la fecha actual
#nombre_archivo = f"{fecha_actual} Informe ArCo.xlsx"

# Construir el nombre del archivo cuando la fecha no es la actual. Aquí solo se modifica la fecha. 
nombre_archivo = "2024 11 01 - Base Original.xlsx"

data_arco = pd.read_excel(nombre_archivo)

In [3]:
data_arco.head()

Código        Sector                                            Entidad  \
0    1794     Hacienda   ADMINISTRADORA COLOMBIANA DE PENSIONES - COLPE...   
1    1800     Hacienda   ADMINISTRADORA COLOMBIANA DE PENSIONES - COLPE...   
2    1797     Hacienda   ADMINISTRADORA COLOMBIANA DE PENSIONES - COLPE...   
3    3689  Agropecuario                  AGENCIA DE DESARROLLO RURAL - ADR   
4    1734  Agropecuario                  AGENCIA DE DESARROLLO RURAL - ADR   

                              Nombre del Instrumento  \
0                       Plan de Educación Financiera   
1                                      Programa Beps   
2  Silverexpo. Feria de entretenimiento y bienest...   
3                              Adecuación de tierras   
4  Fortalecimiento a la prestación del servicio p...   

                                         Descripcion  \
0  A partir del modelo pedagógico de la entidad p...   
1  Los requisitos para vincularse a Hoy y Mañana ...   
2  La feria Silverexpo se realiza en alianza con ...   
3   La adecuación de tierras es el servicio públi...   
4   MEJORAR LA TRANSFERENCIA Y APROPIACIÓN DEL CO...   

                                          Página Web  Antigüedad  \
0         https://www.colpensiones.gov.co/educacion/         5.0   
1              https://www.colpensiones.gov.co/beps/         9.0   
2                            www.colpensiones.gov.co         4.0   
3  https://www.adr.gov.co/atencion-y-servicios-a-...         8.0   
4  https://www.adr.gov.co/atencion-y-servicios-a-...         4.0   

                                           Iteración Emprendedores Mipymes  \
0  Segunda iteración 2023 - Mes de reporte: Marzo...            No      No   
1  Segunda iteración 2023 - Mes de reporte: Marzo...            No      No   
2  Segunda iteración 2023 - Mes de reporte: Marzo...            No      No   
3  Primera iteración 2025 – Mes de reporte: Septi...            No      No   
4  Primera iteración 2024 - Mes de reporte: Septi...            No      No   

   ... 1. Señale cuál o cuáles de las siguientes brechas  \
0  ...                                                No   
1  ...                                                No   
2  ...                                                No   
3  ...                                                Si   
4  ...                                                No   

  2. ¿En el diseño del instrumento se analizó el posible impacto diferenciado?  \
0                                                 No                             
1                                                 No                             
2                                                 No                             
3                                                 No                             
4                                                 No                             

  3. ¿El instrumento incorpora un enfoque interseccional? Recursos fuente PGN  \
0                                                 No                        0   
1                                                 No                        0   
2                                                 No                        0   
3                                                 Si             116422783387   
4                                                 No             122305692809   

  Recursos fuente SGR Recursos fuente Cooperacion  \
0                   0                           0   
1                   0                           0   
2                   0                           0   
3                   0                           0   
4                   0                           0   

  Recursos fuente Esfuerzo Fiscal Recursos fuente Parafiscales  \
0                               0                            0   
1                               0                            0   
2                               0                            0   
3                               0                         

In [4]:
# Get data information
data_arco.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 419 entries, 0 to 418
Data columns (total 71 columns):
 #   Column                                                                        Non-Null Count  Dtype         
---  ------                                                                        --------------  -----         
 0   Código                                                                        419 non-null    int64         
 1   Sector                                                                        418 non-null    object        
 2   Entidad                                                                       419 non-null    object        
 3   Nombre del Instrumento                                                        419 non-null    object        
 4   Descripcion                                                                   419 non-null    object        
 5   Página Web                                                                    419 non-null  

In [5]:
# Selecting the relevant features for recommendation
selected_features = ['Emprendedores',
                 'Mipymes',
                 'Grandes empresas',
                 'Gobierno ',
                 'Academia',
                 'Entidades de soporte',
                 'Personas naturales']
print(selected_features)

['Emprendedores', 'Mipymes', 'Grandes empresas', 'Gobierno ', 'Academia', 'Entidades de soporte', 'Personas naturales']


In [6]:
# Replacing the null valuess with null string
for feature in selected_features:
    data_arco[feature] = data_arco[feature].fillna('')

In [7]:
# combining all the 5 selected features
combined_features = data_arco['Emprendedores'] + ' ' + data_arco['Mipymes'] + ' ' + data_arco['Grandes empresas'] + ' ' + data_arco['Gobierno '] + ' ' + data_arco['Academia'] + ' ' + data_arco['Entidades de soporte']+ ' ' + data_arco['Personas naturales']
combined_features

0      No No No No No No No
1      No No No No No No No
2      No No No No No No No
3      No No No No No No Si
4      No No No No No No Si
               ...         
414    No No No Si Si Si Si
415    No No Si Si Si Si Si
416    No No No Si Si Si Si
417    No Si Si Si No Si No
418    No No No No No No Si
Length: 419, dtype: object

## Construyendo el sistema de recomendación

In [8]:
# converting the text data to feature vectors
vectorizer = TfidfVectorizer()

feature_vectors = vectorizer.fit_transform(combined_features)

In [9]:
print(feature_vectors)

  (0, 0)	1.0
  (1, 0)	1.0
  (2, 0)	1.0
  (3, 1)	0.1621281858740218
  (3, 0)	0.9867697053239923
  (4, 1)	0.1621281858740218
  (4, 0)	0.9867697053239923
  (5, 1)	0.5945097901233671
  (5, 0)	0.8040883716653723
  (6, 1)	0.1621281858740218
  (6, 0)	0.9867697053239923
  (7, 1)	0.3668347714227148
  (7, 0)	0.9302861121586437
  (8, 1)	0.3668347714227148
  (8, 0)	0.9302861121586437
  (9, 1)	0.5945097901233671
  (9, 0)	0.8040883716653723
  (10, 1)	0.3668347714227148
  (10, 0)	0.9302861121586437
  (11, 1)	0.5945097901233671
  (11, 0)	0.8040883716653723
  (12, 1)	0.3668347714227148
  (12, 0)	0.9302861121586437
  (13, 1)	0.3668347714227148
  (13, 0)	0.9302861121586437
  :	:
  (405, 1)	0.1621281858740218
  (405, 0)	0.9867697053239923
  (406, 1)	0.1621281858740218
  (406, 0)	0.9867697053239923
  (407, 1)	1.0
  (408, 0)	1.0
  (409, 1)	0.3668347714227148
  (409, 0)	0.9302861121586437
  (410, 1)	0.795857526821466
  (410, 0)	0.6054839362044375
  (411, 1)	1.0
  (412, 1)	0.9266257884890856
  (412, 0)	0.3759

In [10]:
# getting the similarity scores using cosine similarity
similarity = cosine_similarity(feature_vectors, feature_vectors)

In [11]:
print(similarity)

[[1.         1.         1.         ... 0.60548394 0.60548394 0.98676971]
 [1.         1.         1.         ... 0.60548394 0.60548394 0.98676971]
 [1.         1.         1.         ... 0.60548394 0.60548394 0.98676971]
 ...
 [0.60548394 0.60548394 0.60548394 ... 1.         1.         0.72650414]
 [0.60548394 0.60548394 0.60548394 ... 1.         1.         0.72650414]
 [0.98676971 0.98676971 0.98676971 ... 0.72650414 0.72650414 1.        ]]


In [53]:
# creating a list with all the movie names given in the dataset

list_of_all_titles = data_arco['Nombre del Instrumento'].tolist()
print(list_of_all_titles)

['Plan de Educación Financiera', 'Programa Beps', 'Silverexpo. Feria de entretenimiento y bienestar para Personas Mayores', 'Adecuación de tierras', 'Fortalecimiento a la prestación del servicio público de extensión Agropecuaria', 'FORTALECIMIENTO DE LA GESTIÓN Y APROPIACIÓN DEL CONOCIMIENTO TÉCNICO DE  LOS PROCESOS PRODUCTIVOS AGROPECUARIOS Y RURALES, EN LOS  PRODUCTORES Y LAS A', 'FORTALECIMIENTO DE LA GESTIÓN Y APROPIACIÓN DEL CONOCIMIENTO TÉCNICO DE LOS PROCESOS PRODUCTIVOS AGROPECUARIOS Y RURALES', 'IMPLEMENTACIÓN DE ESTRATEGIAS DE FORTALECIMIENTO Y APOYO COMERCIAL PARA ORGANIZACIONES RURALES A NIVEL NACIONAL', 'Proyectos Integrales de Desarrollo Agropecuario y Rural (PIDAR)', 'Obras por Impuestos', 'Asistencias técnicas realizadas', 'Escuela Virtual de Seguridad Vial', 'ORIENTACIONES TÉCNICAS PARA LA ELABORACIÓN DE PLANES LOCALES DE SEGURIDAD VIAL', 'Red de Observatorios Territoriales de Seguridad Vial (ROT)', 'SEGUIMIENTO A LA IMPLEMENTACIÓN DE LA RUTA DE ATENCIÓN INTEGRAL A VIC

In [77]:
# getting the movie name from the user
instrument_name = input(' Introducir el nombre del instrumento : ')
#instrument_name = 'Información estadística de la temática económica'


In [78]:
# finding the close match for the instrument name given by the user
find_close_match = difflib.get_close_matches(instrument_name, list_of_all_titles)
print(find_close_match)

['Información estadística de la temática de Sociedad', 'Información estadística de la temática económica']


In [15]:
close_match = find_close_match[0]

In [16]:
index_of_the_instrument = data_arco[data_arco['Nombre del Instrumento'] == close_match].index[0]
#index_of_the_instrument

In [17]:
similarity_score = list(enumerate(similarity[index_of_the_instrument]))
similarity_score

[(0, 1.0),
 (1, 1.0),
 (2, 1.0),
 (3, 0.9867697053239923),
 (4, 0.9867697053239923),
 (5, 0.8040883716653724),
 (6, 0.9867697053239923),
 (7, 0.9302861121586437),
 (8, 0.9302861121586437),
 (9, 0.8040883716653724),
 (10, 0.9302861121586437),
 (11, 0.8040883716653724),
 (12, 0.9302861121586437),
 (13, 0.9302861121586437),
 (14, 0.37598490409453983),
 (15, 0.9867697053239923),
 (16, 0.9867697053239923),
 (17, 0.9867697053239923),
 (18, 0.9867697053239923),
 (19, 0.9867697053239923),
 (20, 0.9867697053239923),
 (21, 0.9867697053239923),
 (22, 0.9867697053239923),
 (23, 0.9867697053239923),
 (24, 0.9867697053239923),
 (25, 0.9867697053239923),
 (26, 0.9867697053239923),
 (27, 0.9867697053239923),
 (28, 0.9867697053239923),
 (29, 0.9867697053239923),
 (30, 0.9302861121586437),
 (31, 0.9867697053239923),
 (32, 0.9867697053239923),
 (33, 0.9867697053239923),
 (34, 0.9867697053239923),
 (35, 0.9867697053239923),
 (36, 0.9867697053239923),
 (37, 0.9867697053239923),
 (38, 0.9302861121586437),
 

In [18]:
sorted_similar_instruments = sorted(similarity_score, key = lambda x:x[1], reverse = True)

In [19]:
print('Instrumentos sugeridos para ti : \n')

i = 1
for instrument in sorted_similar_instruments:
    index = instrument[0]
    title_from_index = data_arco.loc[index, 'Nombre del Instrumento']  # Obtiene el nombre del instrumento usando el índice
    if i < 10:
        print(f"{i}. {title_from_index}")
        i += 1


Instrumentos sugeridos para ti : 

1. Plan de Educación Financiera
2. Programa Beps
3. Silverexpo. Feria de entretenimiento y bienestar para Personas Mayores
4. Talleres de educación financiera
5. EnCadena
6. PLATAFORMA COMERCIALIZACION EN LINEA
7. FOMENTO DE ORGANIZACIONES DE ASOCATIVIDAD SOLIDARIA
8. Adecuación de tierras
9. Fortalecimiento a la prestación del servicio público de extensión Agropecuaria
